version: 0.2
            
phases:
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn package
      - aws cloudformation package --template-file sam.yaml --s3-bucket codepipeline-us-east-1-261851842501 --output-template-file sam-output.yaml

artifacts:
  files:
    - target/devops-example-0.0.1-SNAPSHOT.jar
    - sam-output.yaml
