AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM script for the DevOps example
Resources:
  PersonalizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.harrison.devops.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/devops-example-serverless.jar
      Policies: AWSLambdaBasicExecutionRole
      MemorySize: 512
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
